name: 'Container Action'
description: 'Container action demo'
inputs:
  your-name: # id of input
    description: 'your name'
    required: true
    default: 'Chaminda'
outputs:
  time: # id of output
    description: 'The time of the message'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.your-name }